Add workaround for pkcs11
Tectu/botan-cmake pull request #1
Opened 2023-07-21 18:11 UTC by Radioo

This is a workaround for an issue that happens when you include the pkcs11 module. The compiler will complain about three missing headers even in amalgamation builds.

2023-07-21 22:21 UTC, Tectu commented
Interesting... Do you have any idea as to why this issue occurs? This smells like something that would potentially require an upstream fix instead (i.e. a fix in Botan itself).
I'll be looking into this. Could you tell me which version(s) of Botan you encountered this issue with?

2023-07-22 05:01 UTC, Radioo commented
https://github.com/randombit/botan/issues/1447
https://github.com/randombit/botan/issues/976

There have been discussions about this in the past, but it seems nothing has been done about the issue since. I'd give it a shot of fixing it but I'm afraid I'm not qualified to tackle that with my current skill.
I was building the most recent version at the time which was `3.1.1`.
My cmake generation section looks like this:
```
find_package(
        Botan 3.1.1
        REQUIRED
)

botan_generate(
        botan_pkcs11
            pkcs11
)
```
Building on Windows with MSVC.

2023-07-24 12:44 UTC, Tectu commented
Thank you for clarifying this!
This certainly seems like an interesting solution. Personally, I'd agree that this could be considered a "bug" in Botan. However, given the purpose/goal/mission of this CMake integration I also think that it's pretty reasonable to include your fix.
I will sleep one more night over it and most likely merge it.

2023-07-24 12:46 UTC, Tectu requested changes

2023-07-24 12:46 UTC, Tectu commented on cmake/FindBotan.cmake
> +        REQUIRED
Can you please remove these whitespace changes?

2023-07-24 12:46 UTC, Tectu commented on cmake/FindBotan.cmake
> +        STATUS download_status
Can you please remove these whitespace changes?

2023-07-24 12:46 UTC, Tectu commented on cmake/FindBotan.cmake
> +        URL ${DOWNLOAD_URL}
Can you please remove these whitespace changes?

2023-07-24 12:46 UTC, Tectu commented on cmake/FindBotan.cmake
> +            COMMAND ${Python_EXECUTABLE}
Can you please remove these whitespace changes?

2023-07-24 12:46 UTC, Tectu commented on cmake/FindBotan.cmake
> +            PRIVATE
Can you please remove these whitespace changes?

2023-07-24 12:46 UTC, Tectu commented on cmake/FindBotan.cmake
> +            PROPERTIES
Can you please remove these whitespace changes?

2023-07-24 13:35 UTC, Radioo commented
Sorry about that, no idea how those whitespaces got changed.

2023-07-24 14:52 UTC, Tectu approved these changes

2023-07-24 16:06 UTC, merged

2023-07-24 16:07 UTC, Tectu commented
Thank you for your contribution!